package net.sdgfeie.underdiscs.init;

import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;
import net.sdgfeie.underdiscs.Underdiscs;

public class UDSoundEvents {
    public static final SoundEvent MUSIC_DISC_001 = register("music_disc.01");
    public static final SoundEvent MUSIC_DISC_002 = register("music_disc.02");
    public static final SoundEvent MUSIC_DISC_003 = register("music_disc.03");
    public static final SoundEvent MUSIC_DISC_004 = register("music_disc.04");
    public static final SoundEvent MUSIC_DISC_005 = register("music_disc.05");
    public static final SoundEvent MUSIC_DISC_006 = register("music_disc.06");
    public static final SoundEvent MUSIC_DISC_007 = register("music_disc.07");
    public static final SoundEvent MUSIC_DISC_008 = register("music_disc.08");
    public static final SoundEvent MUSIC_DISC_009 = register("music_disc.09");
    public static final SoundEvent MUSIC_DISC_010 = register("music_disc.010");
    public static final SoundEvent MUSIC_DISC_011 = register("music_disc.011");
    public static final SoundEvent MUSIC_DISC_012 = register("music_disc.012");
    public static final SoundEvent MUSIC_DISC_013 = register("music_disc.013");
    public static final SoundEvent MUSIC_DISC_014 = register("music_disc.014");
    public static final SoundEvent MUSIC_DISC_015 = register("music_disc.015");
    public static final SoundEvent MUSIC_DISC_016 = register("music_disc.016");
    public static final SoundEvent MUSIC_DISC_017 = register("music_disc.017");
    public static final SoundEvent MUSIC_DISC_018 = register("music_disc.018");
    public static final SoundEvent MUSIC_DISC_019 = register("music_disc.019");
    public static final SoundEvent MUSIC_DISC_020 = register("music_disc.020");
    public static final SoundEvent MUSIC_DISC_021 = register("music_disc.021");
    public static final SoundEvent MUSIC_DISC_022 = register("music_disc.022");
    public static final SoundEvent MUSIC_DISC_023 = register("music_disc.023");
    public static final SoundEvent MUSIC_DISC_024 = register("music_disc.024");
    public static final SoundEvent MUSIC_DISC_025 = register("music_disc.025");
    public static final SoundEvent MUSIC_DISC_026 = register("music_disc.026");
    public static final SoundEvent MUSIC_DISC_027 = register("music_disc.027");
    public static final SoundEvent MUSIC_DISC_028 = register("music_disc.028");
    public static final SoundEvent MUSIC_DISC_029 = register("music_disc.029");
    public static final SoundEvent MUSIC_DISC_030 = register("music_disc.030");
    public static final SoundEvent MUSIC_DISC_031 = register("music_disc.031");
    public static final SoundEvent MUSIC_DISC_032 = register("music_disc.032");
    public static final SoundEvent MUSIC_DISC_033 = register("music_disc.033");
    public static final SoundEvent MUSIC_DISC_034 = register("music_disc.034");
    public static final SoundEvent MUSIC_DISC_035 = register("music_disc.035");
    public static final SoundEvent MUSIC_DISC_036 = register("music_disc.036");
    public static final SoundEvent MUSIC_DISC_037 = register("music_disc.037");
    public static final SoundEvent MUSIC_DISC_038 = register("music_disc.038");
    public static final SoundEvent MUSIC_DISC_039 = register("music_disc.039");
    public static final SoundEvent MUSIC_DISC_040 = register("music_disc.040");
    public static final SoundEvent MUSIC_DISC_041 = register("music_disc.041");
    public static final SoundEvent MUSIC_DISC_042 = register("music_disc.042");
    public static final SoundEvent MUSIC_DISC_043 = register("music_disc.043");
    public static final SoundEvent MUSIC_DISC_044 = register("music_disc.044");
    public static final SoundEvent MUSIC_DISC_045 = register("music_disc.045");
    public static final SoundEvent MUSIC_DISC_046 = register("music_disc.046");
    public static final SoundEvent MUSIC_DISC_047 = register("music_disc.047");
    public static final SoundEvent MUSIC_DISC_048 = register("music_disc.048");
    public static final SoundEvent MUSIC_DISC_049 = register("music_disc.049");
    public static final SoundEvent MUSIC_DISC_050 = register("music_disc.050");
    public static final SoundEvent MUSIC_DISC_051 = register("music_disc.051");
    public static final SoundEvent MUSIC_DISC_052 = register("music_disc.052");
    public static final SoundEvent MUSIC_DISC_053 = register("music_disc.053");
    public static final SoundEvent MUSIC_DISC_054 = register("music_disc.054");
    public static final SoundEvent MUSIC_DISC_055 = register("music_disc.055");
    public static final SoundEvent MUSIC_DISC_056 = register("music_disc.056");
    public static final SoundEvent MUSIC_DISC_057 = register("music_disc.057");
    public static final SoundEvent MUSIC_DISC_058 = register("music_disc.058");
    public static final SoundEvent MUSIC_DISC_059 = register("music_disc.059");
    public static final SoundEvent MUSIC_DISC_060 = register("music_disc.060");
    public static final SoundEvent MUSIC_DISC_061 = register("music_disc.061");
    public static final SoundEvent MUSIC_DISC_062 = register("music_disc.062");
    public static final SoundEvent MUSIC_DISC_063 = register("music_disc.063");
    public static final SoundEvent MUSIC_DISC_064 = register("music_disc.064");
    public static final SoundEvent MUSIC_DISC_065 = register("music_disc.065");
    public static final SoundEvent MUSIC_DISC_066 = register("music_disc.066");
    public static final SoundEvent MUSIC_DISC_067 = register("music_disc.067");
    public static final SoundEvent MUSIC_DISC_068 = register("music_disc.068");
    public static final SoundEvent MUSIC_DISC_069 = register("music_disc.069");
    public static final SoundEvent MUSIC_DISC_070 = register("music_disc.070");
    public static final SoundEvent MUSIC_DISC_071 = register("music_disc.071");
    public static final SoundEvent MUSIC_DISC_072 = register("music_disc.072");
    public static final SoundEvent MUSIC_DISC_073 = register("music_disc.073");
    public static final SoundEvent MUSIC_DISC_074 = register("music_disc.074");
    public static final SoundEvent MUSIC_DISC_075 = register("music_disc.075");
    public static final SoundEvent MUSIC_DISC_076 = register("music_disc.076");
    public static final SoundEvent MUSIC_DISC_077 = register("music_disc.077");
    public static final SoundEvent MUSIC_DISC_078 = register("music_disc.078");
    public static final SoundEvent MUSIC_DISC_079 = register("music_disc.079");
    public static final SoundEvent MUSIC_DISC_080 = register("music_disc.080");
    public static final SoundEvent MUSIC_DISC_081 = register("music_disc.081");
    public static final SoundEvent MUSIC_DISC_082 = register("music_disc.082");
    public static final SoundEvent MUSIC_DISC_083 = register("music_disc.083");
    public static final SoundEvent MUSIC_DISC_084 = register("music_disc.084");
    public static final SoundEvent MUSIC_DISC_085 = register("music_disc.085");
    public static final SoundEvent MUSIC_DISC_086 = register("music_disc.086");
    public static final SoundEvent MUSIC_DISC_087 = register("music_disc.087");
    public static final SoundEvent MUSIC_DISC_088 = register("music_disc.088");
    public static final SoundEvent MUSIC_DISC_089 = register("music_disc.089");
    public static final SoundEvent MUSIC_DISC_090 = register("music_disc.090");
    public static final SoundEvent MUSIC_DISC_091 = register("music_disc.091");
    public static final SoundEvent MUSIC_DISC_092 = register("music_disc.092");
    public static final SoundEvent MUSIC_DISC_093 = register("music_disc.093");
    public static final SoundEvent MUSIC_DISC_094 = register("music_disc.094");
    public static final SoundEvent MUSIC_DISC_095 = register("music_disc.095");
    public static final SoundEvent MUSIC_DISC_096 = register("music_disc.096");
    public static final SoundEvent MUSIC_DISC_097 = register("music_disc.097");
    public static final SoundEvent MUSIC_DISC_098 = register("music_disc.098");
    public static final SoundEvent MUSIC_DISC_099 = register("music_disc.099");
    public static final SoundEvent MUSIC_DISC_100 = register("music_disc.100");
    public static final SoundEvent MUSIC_DISC_101 = register("music_disc.101");

    private static SoundEvent register(String name) {
        Identifier id = Underdiscs.id(name);
        return Registry.register(Registries.SOUND_EVENT, id, SoundEvent.of(id));
    }
}
